---
- name: Sanity check
  assert:
    that:
      - icinga2_zone is defined

- name: Configure master server
  command: >-
    icinga2 node setup
    --master
    --zone {{ icinga2_zone }}
  args:
    creates: "{{ icinga2_pki_cert_dir }}/{{ inventory_hostname }}.crt"
  notify:
    - restart icinga2

- name: Trigger restart, if any
  meta: flush_handlers

- name: Wait for icinga service pid
  wait_for:
    path: /run/icinga2/icinga2.pid

- name: Wait for icinga service port
  wait_for:
    port: 5665
    connect_timeout: 3
    delay: 3
    timeout: 30
