---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: cluster-centos-master
    image: centos/systemd
    privileged: true
    command: /usr/sbin/init
    networks:
      - name: molecule-icinga2
  - name: cluster-centos-satellite
    image: centos/systemd
    privileged: true
    command: /usr/sbin/init
    networks:
      - name: molecule-icinga2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      cluster-centos-master:
        icinga2_zone: master
        icinga2_role: master
        postgresql_databases:
          - name: icinga
        postgresql_users:
          - name: icinga
            password: icinga
            db: icinga
      cluster-centos-satellite:
        icinga2_zone: red
        icinga2_role: satellite
        icinga2_parent_host: cluster-centos-master
        icinga2_parent_zone: master
        icinga2_endpoints: [ cluster-centos-master ]
scenario:
  name: cluster-centos
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
