---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: monitor-m01
    groups:
      - icinga_master
    image: centos/systemd
    privileged: true
    command: /usr/sbin/init
    networks:
      - name: molecule-icinga2
  - name: monitor-s01
    groups:
      - icinga_satellite
    image: centos/systemd
    privileged: true
    command: /usr/sbin/init
    networks:
      - name: molecule-icinga2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      monitor-s01:
        icinga_parent_fqdn: monitor-m01
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
