---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: master
    groups:
      - icinga_master
    image: centos/systemd
    privileged: true
    command: /usr/sbin/init
    networks:
      - name: molecule-icinga2
  - name: satellite
    groups:
      - icinga_satellite
    image: centos/systemd
    privileged: true
    command: /usr/sbin/init
    networks:
      - name: molecule-icinga2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      satellite:
        icinga_parent_fqdn: master
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
