---
- name: Prepare test requirements
  hosts: all
  tasks:
    - name: Install test requirements
      package:
        name: "{{ item }}"
        state: installed
      with_items:
        - openssl
        - epel-release

- name: Prepare database
  hosts:
    - monitor-m01
  roles:
    - role: geerlingguy.postgresql
