---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: monitor-m01
    image: debian
    networks:
      - name: molecule-icinga2
  - name: monitor-s01
    image: debian
    networks:
      - name: molecule-icinga2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      monitor-m01:
        icinga2_zone: master
        icinga2_role: master
        postgresql_databases:
          - name: icinga
        postgresql_users:
          - name: icinga
            password: icinga
            db: icinga
      monitor-s01:
        icinga2_zone: red
        icinga2_role: satellite
        icinga2_parent_host: monitor-m01
        icinga2_parent_zone: master
        icinga2_endpoints: [ monitor-m01 ]
scenario:
  name: cluster-debian
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
