---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: cluster-debian-master
    image: debian
    networks:
      - name: molecule-icinga2
  - name: cluster-debian-satellite
    image: debian
    networks:
      - name: molecule-icinga2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      cluster-debian-master:
        icinga2_zone: master
        icinga2_role: master
        postgresql_databases:
          - name: icinga
        postgresql_users:
          - name: icinga
            password: icinga
            db: icinga
      cluster-debian-satellite:
        icinga2_zone: red
        icinga2_role: satellite
        icinga2_master_host: cluster-debian-master
        icinga2_parent_host: cluster-debian-master
        icinga2_parent_zone: master
        icinga2_endpoints: [ cluster-debian-master ]
scenario:
  name: cluster-debian
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
