---
- name: Prepare test requirements
  hosts: all
  tasks:
    - name: Install test requirements
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - openssl

- name: Prepare database
  hosts:
    - cluster-debian-master
  roles:
    - role: geerlingguy.postgresql
